# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Top40Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=512)),
                ('artist', models.CharField(max_length=512)),
                ('first_appeared', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
