# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top40', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='top40song',
            unique_together=set([('song', 'artist')]),
        ),
    ]
