# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top40', '0002_auto_20171007_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top40song',
            old_name='song',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='top40song',
            unique_together=set([('title', 'artist')]),
        ),
    ]
